### ISSUE TITLE
Playing a second song, skipping in a song doesn't work: no sound

### ISSUE THREAD

**Issue by Xoliul** [dekztah/sc2#25]
This has happened over the last month: the first song plays ok, once i skip or it automatically goes to the next one, there's no more sound. Same with skipping through a song: sound stops.
Browser latest Firefox, I've just updated Flash as well, no change.

**Comment by dekztah** [comment]
Hi. Flash has no effect whatsoever on sc2, its pure webaudio. i assume firefox has again updated something that breaks their implementation of seeking. since theres is no visible console error, and the playback is working (just silent), they must be sending zeroes to the output for whatever reason. i will check this sometime later, but i assume FF next update will fix this. until then, use chrome :)

**Comment by dekztah** [comment]
i have checked again and this works now in firefox 53
